config/routes.rb
LMSSys::Application.routes.draw do

  get "json_reports/index"
  match 'json_reports/index', to: 'json_reports#index', via: :get, as: 'json_reports_index'
  match 'json_reports/show/:user_id', to: 'json_reports#show', via: :get, as: 'json_reports_show'

  match 'user_sync_photo/update_photo', to: 'user_sync_photo#update_photo', via: :post, as: 'user_sync_photo_update'
  resources :bd_backups, only: [:index, :new, :create, :destroy]
  match 'bd_backups/:database/show_tables', to: 'bd_backups#get_tables_from_database', via: :post, as: 'bd_backups_get_tables_from_database'

  resources :brc_mails

  match 'single_sign_on', to: 'static_pages#single_sign_on', via: :post, as: 'single_sign_on'
  resources :user_delete_types

  resources :liq_items

  resources :liq_processes
  match 'liq_processes/:id/load_data_from_payroll', to: 'liq_processes#load_data_from_payroll', via: :post, as: 'liq_process_load_data_from_payroll'
  match 'liq_processes/:id/detail', to: 'liq_processes#show_detail', via: :get, as: 'liq_process_show_detail'
  match 'liq_processes/:id/clean_items', to: 'liq_processes#clean_items', via: :get, as: 'liq_process_clean_items'

  resources :user_delete_reasons

  resources :scholarship_applications, except: [:new, :index]
  match 'scholarship_applications/go/:scholarship_process_id/:subject_user_id', to: 'scholarship_applications#go_to', via: :get, as: 'scholarship_application_go_to'

  resources :scholarship_lists

  resources :scholarship_processes
  match 'scholarship_processes/:id/edit_groups', to: 'scholarship_processes#edit_groups', via: :get, as: 'scholarship_process_edit_groups'
  match 'scholarship_processes/:id/update_groups', to: 'scholarship_processes#update_groups', via: :put, as: 'scholarship_process_update_groups'
  match 'scholarship_manager_processes/', to: 'scholarship_manager_processes#index', via: :get, as: 'scholarship_manager_processes'
  match 'scholarship_manager_processes/:id', to: 'scholarship_manager_processes#show', via: :get, as: 'scholarship_manager_processes_show'
  match 'scholarship_manager_processes/application/:scholarship_application_id', to: 'scholarship_manager_processes#show_application', via: :get, as: 'scholarship_manager_processes_show_application'
  match 'scholarship_manager_processes/application/:scholarship_application_id/evaluate', to: 'scholarship_manager_processes#evaluate_application', via: :post, as: 'scholarship_manager_processes_evaluate_application'
  match 'scholarship_manager_processes/:id/applications/report', to: 'scholarship_manager_processes#applications_list_report', via: :get, as: 'scholarship_manager_processes_applications_list_report'
  match 'scholarship_manager_processes/application/:scholarship_application_id/revert', to: 'scholarship_manager_processes#revert_evaluation', via: :get, as: 'scholarship_manager_processes_revert_evaluation'
  match 'scholarship_manager_processes/application/:scholarship_application_id/delete', to: 'scholarship_manager_processes#delete_application', via: :get, as: 'scholarship_manager_processes_delete_application'
  match 'scholarship_manager_processes/:id/massive_evaluation', to: 'scholarship_manager_processes#massive_evaluation', via: :post, as: 'scholarship_manager_processes_massive_evaluation'
  resources :sel_notification_templates

  resources :password_policies

  match 'migra_security/p4', to: 'migra_security#paso_4', via: :get, as: 'migra_security_p4'
  match 'migra_security/p5', to: 'migra_security#paso_5', via: :get, as: 'migra_security_p5'
  match 'migra_security/p6', to: 'migra_security#paso_6', via: :get, as: 'migra_security_p6'
  match 'migra_security/p7', to: 'migra_security#paso_7', via: :get, as: 'migra_security_p7'
  match 'migra_security/p8', to: 'migra_security#paso_8', via: :get, as: 'migra_security_p8'
  match 'migra_security/p9', to: 'migra_security#paso_9', via: :get, as: 'migra_security_p9'

  match 'temporal_processing/puestos_visanet', to: 'temporal_processing#puestos_visanet', via: :get, as: 'temporal_processing_puestos_visanet'

  resources :brc_apv_institutions

  resources :secu_cohades

  match 'brc_define/list_processes', to: 'brc_define#list_processes', via: :get, as: 'brc_define_list_processes'
  match 'brc_define/list_people/:brc_process_id', to: 'brc_define#list_people', via: :get, as: 'brc_define_list_people'

  match 'brc_define/massive_assign_members/:brc_process_id', to: 'brc_define#massive_assign_members', via: :get, as: 'brc_define_massive_assign_members'
  match 'brc_define/massive_assign_members/:brc_process_id', to: 'brc_define#massive_assign_members', via: :post, as: 'brc_define_massive_assign_members'
  match 'brc_define/download_massive_assign_members_excel_format', to: 'brc_define#download_massive_assign_members_excel_format', via: :get, as: 'brc_define_download_massive_assign_members_excel_format'
  match 'brc_define/download_categories_excel', to: 'brc_define#download_categories_excel', via: :get, as: 'brc_define_download_categories_excel'

  match 'brc_define/remove_members/:brc_process_id', to: 'brc_define#remove_members', via: :post, as: 'brc_define_remove_members'

  match 'brc_define/show/:brc_member_id', to: 'brc_define#show', via: :get, as: 'brc_define_show'
  match 'brc_define/new/:brc_member_id', to: 'brc_define#new', via: :get, as: 'brc_define_new'
  match 'brc_define/create/:brc_member_id', to: 'brc_define#create', via: :post, as: 'brc_define_create'
  match 'brc_define/edit/:brc_bonus_item_id', to: 'brc_define#edit', via: :get, as: 'brc_define_edit'
  match 'brc_define/update/:brc_bonus_item_id', to: 'brc_define#update', via: :put, as: 'brc_define_update'
  match 'brc_define/delete/:brc_bonus_item_id', to: 'brc_define#delete', via: :get, as: 'brc_define_delete'
  match 'brc_define/finish/:brc_member_id', to: 'brc_define#finish', via: :post, as: 'brc_define_finish'

  match 'brc_define/massive_finish/:brc_process_id', to: 'brc_define#massive_finish', via: :post, as: 'brc_define_massive_finish'

  match 'brc_define/download_defined_bonus/:brc_process_id', to: 'brc_define#download_defined_bonus', via: :get, as: 'brc_define_download_defined_bonus'

  match 'brc_validate/list_processes', to: 'brc_validate#list_processes', via: :get, as: 'brc_validate_list_processes'
  match 'brc_validate/list_people/:brc_process_id', to: 'brc_validate#list_people', via: :get, as: 'brc_validate_list_people'
  match 'brc_validate/show/:brc_member_id', to: 'brc_validate#show', via: :get, as: 'brc_validate_show'
  match 'brc_validate/finish/:brc_member_id', to: 'brc_validate#finish', via: :post, as: 'brc_validate_finish'

  match 'brc_validate/massive_validate/:brc_process_id', to: 'brc_validate#massive_validate', via: :get, as: 'brc_validate_massive_validate'
  match 'brc_validate/massive_validate/:brc_process_id', to: 'brc_validate#massive_validate', via: :post, as: 'brc_validate_massive_validate'
  match 'brc_validate/download_massive_validate_excel_format/:brc_process_id', to: 'brc_validate#download_massive_validate_excel_format', via: :get, as: 'brc_validate_download_massive_validate_excel_format'

  match 'brc_validate/massive_validate_categ/:brc_process_id/:cv_id/:brc_category_id', to: 'brc_validate#massive_validate_categ', via: :post, as: 'brc_validate_massive_validate_categ'
  match 'brc_validate/validate_item/:brc_process_id/:cv_id/:brc_category_id/:brc_bonus_item_id', to: 'brc_validate#validate_item', via: :post, as: 'brc_validate_validate_item'

  resources :brc_categories

  match 'brc/massive_assign_members/:brc_process_id', to: 'brc_managing#massive_assign_members', via: :get, as: 'brc_managing_massive_assign_members'
  match 'brc/massive_assign_members/:brc_process_id', to: 'brc_managing#massive_assign_members', via: :post, as: 'brc_managing_massive_assign_members'
  match 'brc/download_massive_assign_members_excel_format', to: 'brc_managing#download_massive_assign_members_excel_format', via: :get, as: 'brc_managing_download_massive_assign_members_excel_format'

  match 'brc/massive_assign_definers/:brc_process_id', to: 'brc_managing#massive_assign_definers', via: :get, as: 'brc_managing_massive_assign_definers'
  match 'brc/massive_assign_definers/:brc_process_id', to: 'brc_managing#massive_assign_definers', via: :post, as: 'brc_managing_massive_assign_definers'
  match 'brc/download_massive_assign_definers_excel_format', to: 'brc_managing#download_massive_assign_definers_excel_format', via: :get, as: 'brc_managing_download_massive_assign_definers_excel_format'

  match 'brc/download_bonus_defined_excel_format/:brc_process_id', to: 'brc_managing#download_bonus_defined_excel_format', via: :get, as: 'brc_managing_download_bonus_defined_excel_format'
  match 'brc/massive_charge_bonus_calculated/:brc_process_id', to: 'brc_managing#massive_charge_bonus_calculated', via: :get, as: 'brc_managing_massive_charge_bonus_calculated'
  match 'brc/massive_charge_bonus_calculated/:brc_process_id', to: 'brc_managing#massive_charge_bonus_calculated', via: :post, as: 'brc_managing_massive_charge_bonus_calculated'
  match 'brc/download_massive_charge_bonus_calculated_excel_format', to: 'brc_managing#download_massive_charge_bonus_calculated_excel_format', via: :get, as: 'brc_managing_download_massive_charge_bonus_calculated_excel_format'

  match 'brc/download_bonus_chosen_excel_format/:brc_process_id', to: 'brc_managing#download_bonus_chosen_excel_format', via: :get, as: 'brc_managing_download_bonus_chosen_excel_format'
  match 'brc/download_bonus_chosen_excel_format_2/:brc_process_id', to: 'brc_managing#download_bonus_chosen_excel_format_2', via: :get, as: 'brc_managing_download_bonus_chosen_excel_format_2'

  match 'brc/massive_choose_list/:brc_process_id', to: 'brc_managing#massive_choose_list', via: :get, as: 'brc_managing_massive_choose_list'
  match 'brc/massive_choose/:brc_process_id', to: 'brc_managing#massive_choose', via: :post, as: 'brc_managing_massive_choose'

app/controllers/scholarship_processes_controller.rb
class ScholarshipProcessesController < ApplicationController

  before_filter :authenticate_user
  before_filter :authenticate_user_admin

  # GET /scholarship_processes
  # GET /scholarship_processes.json
  def index
    @scholarship_processes = ScholarshipProcess.all
  end

  # GET /scholarship_processes/1
  # GET /scholarship_processes/1.json
  def show
    @scholarship_process = ScholarshipProcess.find(params[:id])
  end

  # GET /scholarship_processes/new
  # GET /scholarship_processes/new.json
  def new
    @scholarship_process = ScholarshipProcess.new
  end

  # GET /scholarship_processes/1/edit
  def edit
    @scholarship_process = ScholarshipProcess.find(params[:id])
  end

  # POST /scholarship_processes
  # POST /scholarship_processes.json
  def create
    @scholarship_process = ScholarshipProcess.new(params[:scholarship_process])
    if @scholarship_process.save
      flash[:success] = 'Proceso creado correctamente'
      redirect_to @scholarship_process
    else
      flash.now[:danger] = 'El proceso no pudo ser creado correctamente'
      render 'new'
    end
  end

  # PUT /scholarship_processes/1
  # PUT /scholarship_processes/1.json
  def update
    @scholarship_process = ScholarshipProcess.find(params[:id])

    if @scholarship_process.update_attributes(params[:scholarship_process])
      flash[:success] = 'Proceso actualizado correctamente'
      redirect_to @scholarship_process
    else
      flash.now[:danger] = 'El proceso no pudo ser actualizado correctamente'
      render 'edit'
    end
  end

  # DELETE /scholarship_processes/1
  # DELETE /scholarship_processes/1.json
  def destroy
    @scholarship_process = ScholarshipProcess.find(params[:id])
    @scholarship_process.destroy
    flash[:success] = 'Proceso eliminado correctamente'
    redirect_to scholarship_processes_path
  end

  def edit_groups
    @scholarship_process = ScholarshipProcess.find(params[:id])
  end

  def update_groups
    @scholarship_process = ScholarshipProcess.find(params[:id])
    if @scholarship_process.update_attributes(params[:scholarship_process])
      flash[:success] = 'Proceso actualizado correctamente'
      redirect_to @scholarship_process
    else
      flash.now[:danger] = 'El proceso no pudo ser actualizado correctamente'
      render 'edit_groups'
    end
  end
end

app/helpers/scholarship_processes_helper.rb
module ScholarshipProcessesHelper

  def icon_scholarship_module_html_safe
    icon_scholarship_module.html_safe
  end

  def icon_scholarship_module
    '<i class="' + icon_scholarship_module_class + '"></i>'
  end

  def icon_scholarship_module_class
    'fa fa-graduation-cap'
  end

  def link_to_remove_scholarship_item_group(name, f)
    f.hidden_field(:_destroy) + link_to(name, '#', onclick: "remove_scholarship_item_group(this)")
  end

  def link_to_add_scholarship_item_group(name, f)
    scholarship_item_group = ScholarshipItemGroup.new
    fields = f.fields_for(:scholarship_item_groups, scholarship_item_group, :child_index => "new_scholarship_item_group") do |builder|
      render('scholarship_processes/form_group', :f => builder)
    end
    link_to(name, '#', onclick: "add_scholarship_item_group(this, \"#{escape_javascript(fields)}\")")
  end

  def link_to_remove_scholarship_application_item(name, f)
    f.hidden_field(:_destroy) + link_to(name, '#', onclick: "remove_scholarship_application_item(this)")
  end

  def link_to_add_scholarship_application_item(name, f)
    scholarship_application_item = ScholarshipApplicationItem.new
    fields = f.fields_for(:scholarship_application_items, scholarship_application_item, :child_index => "new_scholarship_application_item") do |builder|
      render('scholarship_processes/form_item', :f => builder)
    end
    link_to(name, '#', onclick: "add_scholarship_application_item(this, \"#{escape_javascript(fields)}\")")
  end

end

app/views/scholarship_processes/_form.html.erb
<%= form_for @scholarship_process, class: 'form-horizontal' do |f| %>

  <div class="panel panel-default">
    <div class="panel-body">

      <legend>Datos del Proceso</legend>

      <%= render 'shared/error_messages', object: f.object %>
      <div class="row form-group <%= field_with_errors f, :name %>">
        <%= f.label :name, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="row form-group <%= field_with_errors f, :description %>">
        <%= f.label :description, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_area :description, :rows => 3, class: 'form-control' %>
        </div>
      </div>
      <div class="row form-group <%= field_with_errors f, :app_form_description %>">
        <%= f.label :app_form_description, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_area :app_form_description, :rows => 3, class: 'form-control' %>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :active, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= render partial: 'shared/bootstrap_si_no_switch', :locals => {:f => f, :field => :active} %>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :app_from_date, class: 'col-md-3 control-label'  %>
        <div class="col-md-9">
          <div id="sel_process_from_date" class="input-group date" style="cursor:pointer">
            <%= f.text_field :app_from_date, value: @scholarship_process.app_from_date ? @scholarship_process.app_from_date.strftime('%d/%m/%Y') : lms_time.strftime('%d/%m/%Y'), data: {format: 'dd/MM/yyyy'}, class: 'form-control datepicker', readonly: true, style: 'cursor:pointer'  %>
            <span class="input-group-addon">
              <i class="fa fa-calendar"></i>
            </span>
          </div>
        </div>
      </div>
      <div class="row form-group">
        <%= f.label :app_to_date, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <div id="sel_process_from_date" class="input-group date" style="cursor: pointer">
            <%= f.text_field :app_to_date, value: @scholarship_process.app_to_date ? @scholarship_process.app_to_date.strftime('%d/%m/%Y') : lms_time.strftime('%d/%m/%Y'), data: {format: 'dd/MM/yyyy'}, class: 'form-control datepicker', readonly: true, style: 'cursor:pointer'  %>
            <span class="input-group-addon">
              <i class="fa fa-calendar"></i>
            </span>
          </div>
        </div>
      </div>

    </div>
    <div class="panel-footer clearfix">
      <div class="pull-right">
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

<script>
    $('.datepicker').datetimepicker({
        language: 'es',
        pickTime: false
    });
</script>

app/views/scholarship_processes/_form_group.html.erb
<div class="panel panel-primary group">
  <div class="panel-body">
    <div class="row form-group <%= field_with_errors f, :position %>">
      <%= f.label :position, class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.number_field :position, class: 'form-control' %>
      </div>
    </div>
    <div class="row form-group <%= field_with_errors f, :name %>">
      <%= f.label :name, class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="row form-group <%= field_with_errors f, :description %>">
      <%= f.label :description, class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_area :description, :rows => 3, class: 'form-control' %>
      </div>
    </div>

    <div class="panel panel-default items_container">
      <div class="panel-body item_container">
        <legend>Items</legend>
        <%= f.fields_for :scholarship_application_items do |f_item| %>
          <%= render partial: 'form_item', locals: {f: f_item} %>
        <% end %>
      </div>
      <div class="panel-footer clearfix">
        <div class="pull-right">
          <%= link_to_add_scholarship_application_item 'Añadir item', f %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-footer clearfix">
    <div class="pull-right">
      <%= link_to_remove_scholarship_item_group 'Eliminar grupo', f %>
    </div>
  </div>
</div>

app/views/scholarship_processes/_form_groups.html.erb
<%= form_for @scholarship_process, url: scholarship_process_update_groups_path(@scholarship_process), class: 'form-horizontal' do |f| %>

  <div class="panel panel-default groups_container">
    <div class="panel-body group_container">
      <%= render 'shared/error_messages', object: f.object %>
      <legend>Datos del Formulario</legend>
      <%= f.fields_for :scholarship_item_groups do |f_group| %>
        <%= render partial: 'form_group', locals: {f: f_group} %>
      <% end %>
    </div>
    <div class="panel-footer clearfix">
      <div class="pull-right">
        <%= link_to_add_scholarship_item_group 'Añadir grupo', f %>
        &nbsp;&nbsp;
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>


<script>
    //item-groups
    function remove_scholarship_item_group(link) {
        var r = confirm("¿Está seguro?");
        if (r == true) {
            $(link).prev('input[type=hidden]').val(1)
            $(link).closest('.group').hide();
        }
    }

    function add_scholarship_item_group(link, content) {
        var new_id = new Date().getTime();
        var regexp = new RegExp('new_scholarship_item_group', 'g')
        $(link).closest('.groups_container').find('.group_container').append(content.replace(regexp, new_id))
    }

    //items
    function remove_scholarship_application_item(link) {
        var r = confirm("¿Está seguro?");
        if (r == true) {
            $(link).prev('input[type=hidden]').val(1)
            $(link).closest('.item').hide();
        }
    }

    function add_scholarship_application_item(link, content) {
        var new_id = new Date().getTime();
        var regexp = new RegExp('new_scholarship_application_item', 'g')
        $(link).closest('.items_container').find('.item_container').append(content.replace(regexp, new_id))
        initialize_datepickers()
    }

    function initialize_datepickers() {
        $('.date_picker').datetimepicker({
            language: 'es',
            pickTime: false
        });
        $('.date_picker').removeClass('datepicker')
    }

    $( document ).ready(function() {
        initialize_datepickers()
    });
</script>

app/views/scholarship_processes/_form_range.html.erb
<tr>
  <td>
    <%= f.number_field :position, class: 'form-control' %>
  </td>
  <td>
    <%= f.hidden_field :scholarship_list_item_id %>
    <%= f.object.scholarship_list_item.name %>
  </td>
  <td>
    <% option_min_sign_array = ScholarshipApplicationItemRange.min_sign_options.each_with_index.map {|min_sign_option, index| [min_sign_option, index]} %>
    <%= f.select :min_sign, options_for_select(option_min_sign_array, f.object.min_sign), class: 'form-control' %>
  </td>
  <td>
    <%= f.number_field :min_val, class: 'form-control' %>
  </td>
  <td>
    <% option_max_sign_array = ScholarshipApplicationItemRange.max_sign_options.each_with_index.map {|min_sign_option, index| [min_sign_option, index]} %>
    <%= f.select :max_sign, options_for_select(option_max_sign_array, f.object.max_sign), class: 'form-control' %>
  </td>
  <td>
    <%= f.number_field :max_val, class: 'form-control' %>
  </td>
  <td>
    <%= f.check_box :is_default, value: 1 %>
  </td>
</tr>

app/views/scholarship_processes/_show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <legend>
      Datos del Proceso
    </legend>
    <div class="row">
      <div class="col-md-3">
        <strong><%= t('activerecord.attributes.scholarship_process.name') %></strong>
      </div>
      <div class="col-md-9">
        <%= @scholarship_process.name %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-3">
        <strong><%= t('activerecord.attributes.scholarship_process.description') %></strong>
      </div>
      <div class="col-md-9">
        <%= @scholarship_process.description.html_safe %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-3">
        <strong><%= t('activerecord.attributes.scholarship_process.app_form_description') %></strong>
      </div>
      <div class="col-md-9">
        <%= @scholarship_process.app_form_description.html_safe %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-3">
        <strong><%= t('activerecord.attributes.scholarship_process.active') %></strong>
      </div>
      <div class="col-md-9">
        <%= label_yes_not(@scholarship_process.active) %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-3">
        <strong><%= t('activerecord.attributes.scholarship_process.app_from_date') %></strong>
      </div>
      <div class="col-md-9">
        <%= (localize @scholarship_process.app_from_date, format: :day_snmonth_year) %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-3">
        <strong><%= t('activerecord.attributes.scholarship_process.app_to_date') %></strong>
      </div>
      <div class="col-md-9">
        <%= (localize @scholarship_process.app_to_date, format: :day_snmonth_year) %>
      </div>
    </div>
    <br>

  </div>
  <% if defined?(show_footer) && show_footer %>
  <div class="panel-footer clearfix">

    <div class="pull-right">
      <%= link_to 'Eliminar', @scholarship_process, :method => :delete, class: 'btn btn-danger', :confirm => '¿Está seguro? Las postulaciones se eliminarán definitivamente.' if true %>
      &nbsp;&nbsp;
      <%= link_to 'Editar', edit_scholarship_process_path(@scholarship_process) %>
    </div>

  </div>
    <% end %>
</div>

app/views/scholarship_processes/index.html.erb
<h1 class="page-title txt-color-blueDark">
  <%= icon_scholarship_module_html_safe %>
  Becas
  <span>> Procesos de postulación a Becas</span>
</h1>

<div class="panel panel-default">
  <div class="panel-body">


    <legend>Lista de Procesos</legend>

    <table class="table table-striped table-hover table-bordered">

      <thead>

      <tr>

        <th><%= t('activerecord.attributes.scholarship_process.name') %></th>
        <th><%= t('activerecord.attributes.scholarship_process.description') %></th>
        <th><%= t('activerecord.attributes.scholarship_process.active') %></th>
        <th><%= t('activerecord.attributes.scholarship_process.app_from_date') %></th>
        <th><%= t('activerecord.attributes.scholarship_process.app_to_date') %></th>
        <th>
          <%= link_to 'Crear un nuevo proceso', new_scholarship_process_path %>
        </th>
      </tr>
      </thead>

      <tbody>

      <% @scholarship_processes.each do |process| %>
        <tr>
          <td><%= process.name %></td>
          <td><%= process.description.html_safe %></td>
          <td><%= icon_true_false_in_show(process.active) %></td>
          <td>
            <span class="label label-success">
                  <%= (localize process.app_from_date, format: :day_snmonth_year) %>
                </span>
          </td>
          <td>
            <span class="label label-success">
                  <%= (localize process.app_to_date, format: :day_snmonth_year) %>
                </span>
          </td>
          <td><%= link_to 'Configurar', process %></td>
        </tr>
      <% end %>
      </table>
  </div>
</div>

app/views/scholarship_processes/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= link_to '<i class="fa fa-arrow-left"></i> Volver a la lista de Procesos'.html_safe, scholarship_processes_path, class: 'btn btn-default', tabindex: '-1' %>
  </div>
  <div class="col-md-6">
    <h1 class="page-title txt-color-blueDark">
      <%= icon_scholarship_module_html_safe %>
      <%= @scholarship_process.name %>
      <span>> Gestionar proceso </span>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: 'show', locals: {show_footer: true} %>
  </div>
</div>

<br>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-body">
        <legend>
          Items del Formulario de postulación
        </legend>
        <% @scholarship_process.scholarship_item_groups.each do |group| %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= group.name %>
            </div>
            <div class="panel-body">
              <%= group.description.html_safe %>
              <table class="table table-bordered">
                <thead>
                <tr>
                  <th><%= t('activerecord.attributes.scholarship_application_item.position') %></th>
                  <th><%= t('activerecord.attributes.scholarship_application_item.name') %></th>
                  <th><%= t('activerecord.attributes.scholarship_application_item.mandatory') %></th>
                  <th><%= t('activerecord.attributes.scholarship_application_item.item_type') %></th>
                </tr>
                </thead>
                <tbody>
                <% group.scholarship_application_items.each do |item| %>
                  <tr>
                    <td><%= item.position %></td>
                    <td><%= item.name %></td>
                    <td><%= label_yes_not item.mandatory %></td>
                    <td>
                      <%= ScholarshipApplicationItem.alternative_item_type_hash[item.item_type][:name] %>
                      <% if ScholarshipApplicationItem.alternative_item_type_hash[item.item_type][:need_a_list] %>
                      <br><span class="label label-success"><%= item.scholarship_list.name %></span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>



            </div>
          </div>
        <% end %>
      </div>
      <div class="panel-footer clearfix">
        <div class="pull-right">
          <%= link_to 'Configurar Grupos', scholarship_process_edit_groups_path(@scholarship_process) %>
        </div>
      </div>
    </div>
  </div>
</div>