config/routes.rb
LMSSys::Application.routes.draw do

  get "json_reports/index"
  match 'json_reports/index', to: 'json_reports#index', via: :get, as: 'json_reports_index'
  match 'json_reports/show/:user_id', to: 'json_reports#show', via: :get, as: 'json_reports_show'

  match 'user_sync_photo/update_photo', to: 'user_sync_photo#update_photo', via: :post, as: 'user_sync_photo_update'
  resources :bd_backups, only: [:index, :new, :create, :destroy]
  match 'bd_backups/:database/show_tables', to: 'bd_backups#get_tables_from_database', via: :post, as: 'bd_backups_get_tables_from_database'

  resources :brc_mails

  match 'single_sign_on', to: 'static_pages#single_sign_on', via: :post, as: 'single_sign_on'
  resources :user_delete_types

  resources :liq_items

  resources :liq_processes
  match 'liq_processes/:id/load_data_from_payroll', to: 'liq_processes#load_data_from_payroll', via: :post, as: 'liq_process_load_data_from_payroll'
  match 'liq_processes/:id/detail', to: 'liq_processes#show_detail', via: :get, as: 'liq_process_show_detail'
  match 'liq_processes/:id/clean_items', to: 'liq_processes#clean_items', via: :get, as: 'liq_process_clean_items'

  resources :user_delete_reasons

  resources :scholarship_applications, except: [:new, :index]
  match 'scholarship_applications/go/:scholarship_process_id/:subject_user_id', to: 'scholarship_applications#go_to', via: :get, as: 'scholarship_application_go_to'

  resources :scholarship_lists

  resources :scholarship_processes
  match 'scholarship_processes/:id/edit_groups', to: 'scholarship_processes#edit_groups', via: :get, as: 'scholarship_process_edit_groups'
  match 'scholarship_processes/:id/update_groups', to: 'scholarship_processes#update_groups', via: :put, as: 'scholarship_process_update_groups'
  match 'scholarship_manager_processes/', to: 'scholarship_manager_processes#index', via: :get, as: 'scholarship_manager_processes'
  match 'scholarship_manager_processes/:id', to: 'scholarship_manager_processes#show', via: :get, as: 'scholarship_manager_processes_show'
  match 'scholarship_manager_processes/application/:scholarship_application_id', to: 'scholarship_manager_processes#show_application', via: :get, as: 'scholarship_manager_processes_show_application'
  match 'scholarship_manager_processes/application/:scholarship_application_id/evaluate', to: 'scholarship_manager_processes#evaluate_application', via: :post, as: 'scholarship_manager_processes_evaluate_application'
  match 'scholarship_manager_processes/:id/applications/report', to: 'scholarship_manager_processes#applications_list_report', via: :get, as: 'scholarship_manager_processes_applications_list_report'
  match 'scholarship_manager_processes/application/:scholarship_application_id/revert', to: 'scholarship_manager_processes#revert_evaluation', via: :get, as: 'scholarship_manager_processes_revert_evaluation'
  match 'scholarship_manager_processes/application/:scholarship_application_id/delete', to: 'scholarship_manager_processes#delete_application', via: :get, as: 'scholarship_manager_processes_delete_application'
  match 'scholarship_manager_processes/:id/massive_evaluation', to: 'scholarship_manager_processes#massive_evaluation', via: :post, as: 'scholarship_manager_processes_massive_evaluation'
  resources :sel_notification_templates

  resources :password_policies

  match 'migra_security/p4', to: 'migra_security#paso_4', via: :get, as: 'migra_security_p4'
  match 'migra_security/p5', to: 'migra_security#paso_5', via: :get, as: 'migra_security_p5'
  match 'migra_security/p6', to: 'migra_security#paso_6', via: :get, as: 'migra_security_p6'
  match 'migra_security/p7', to: 'migra_security#paso_7', via: :get, as: 'migra_security_p7'
  match 'migra_security/p8', to: 'migra_security#paso_8', via: :get, as: 'migra_security_p8'
  match 'migra_security/p9', to: 'migra_security#paso_9', via: :get, as: 'migra_security_p9'

  match 'temporal_processing/puestos_visanet', to: 'temporal_processing#puestos_visanet', via: :get, as: 'temporal_processing_puestos_visanet'

  resources :brc_apv_institutions

  resources :secu_cohades

  match 'brc_define/list_processes', to: 'brc_define#list_processes', via: :get, as: 'brc_define_list_processes'
  match 'brc_define/list_people/:brc_process_id', to: 'brc_define#list_people', via: :get, as: 'brc_define_list_people'

  match 'brc_define/massive_assign_members/:brc_process_id', to: 'brc_define#massive_assign_members', via: :get, as: 'brc_define_massive_assign_members'
  match 'brc_define/massive_assign_members/:brc_process_id', to: 'brc_define#massive_assign_members', via: :post, as: 'brc_define_massive_assign_members'
  match 'brc_define/download_massive_assign_members_excel_format', to: 'brc_define#download_massive_assign_members_excel_format', via: :get, as: 'brc_define_download_massive_assign_members_excel_format'
  match 'brc_define/download_categories_excel', to: 'brc_define#download_categories_excel', via: :get, as: 'brc_define_download_categories_excel'

  match 'brc_define/remove_members/:brc_process_id', to: 'brc_define#remove_members', via: :post, as: 'brc_define_remove_members'

  match 'brc_define/show/:brc_member_id', to: 'brc_define#show', via: :get, as: 'brc_define_show'
  match 'brc_define/new/:brc_member_id', to: 'brc_define#new', via: :get, as: 'brc_define_new'
  match 'brc_define/create/:brc_member_id', to: 'brc_define#create', via: :post, as: 'brc_define_create'
  match 'brc_define/edit/:brc_bonus_item_id', to: 'brc_define#edit', via: :get, as: 'brc_define_edit'
  match 'brc_define/update/:brc_bonus_item_id', to: 'brc_define#update', via: :put, as: 'brc_define_update'
  match 'brc_define/delete/:brc_bonus_item_id', to: 'brc_define#delete', via: :get, as: 'brc_define_delete'
  match 'brc_define/finish/:brc_member_id', to: 'brc_define#finish', via: :post, as: 'brc_define_finish'

  match 'brc_define/massive_finish/:brc_process_id', to: 'brc_define#massive_finish', via: :post, as: 'brc_define_massive_finish'

  match 'brc_define/download_defined_bonus/:brc_process_id', to: 'brc_define#download_defined_bonus', via: :get, as: 'brc_define_download_defined_bonus'

  match 'brc_validate/list_processes', to: 'brc_validate#list_processes', via: :get, as: 'brc_validate_list_processes'
  match 'brc_validate/list_people/:brc_process_id', to: 'brc_validate#list_people', via: :get, as: 'brc_validate_list_people'
  match 'brc_validate/show/:brc_member_id', to: 'brc_validate#show', via: :get, as: 'brc_validate_show'
  match 'brc_validate/finish/:brc_member_id', to: 'brc_validate#finish', via: :post, as: 'brc_validate_finish'

  match 'brc_validate/massive_validate/:brc_process_id', to: 'brc_validate#massive_validate', via: :get, as: 'brc_validate_massive_validate'
  match 'brc_validate/massive_validate/:brc_process_id', to: 'brc_validate#massive_validate', via: :post, as: 'brc_validate_massive_validate'
  match 'brc_validate/download_massive_validate_excel_format/:brc_process_id', to: 'brc_validate#download_massive_validate_excel_format', via: :get, as: 'brc_validate_download_massive_validate_excel_format'

  match 'brc_validate/massive_validate_categ/:brc_process_id/:cv_id/:brc_category_id', to: 'brc_validate#massive_validate_categ', via: :post, as: 'brc_validate_massive_validate_categ'
  match 'brc_validate/validate_item/:brc_process_id/:cv_id/:brc_category_id/:brc_bonus_item_id', to: 'brc_validate#validate_item', via: :post, as: 'brc_validate_validate_item'

  resources :brc_categories

  match 'brc/massive_assign_members/:brc_process_id', to: 'brc_managing#massive_assign_members', via: :get, as: 'brc_managing_massive_assign_members'
  match 'brc/massive_assign_members/:brc_process_id', to: 'brc_managing#massive_assign_members', via: :post, as: 'brc_managing_massive_assign_members'
  match 'brc/download_massive_assign_members_excel_format', to: 'brc_managing#download_massive_assign_members_excel_format', via: :get, as: 'brc_managing_download_massive_assign_members_excel_format'

  match 'brc/massive_assign_definers/:brc_process_id', to: 'brc_managing#massive_assign_definers', via: :get, as: 'brc_managing_massive_assign_definers'
  match 'brc/massive_assign_definers/:brc_process_id', to: 'brc_managing#massive_assign_definers', via: :post, as: 'brc_managing_massive_assign_definers'
  match 'brc/download_massive_assign_definers_excel_format', to: 'brc_managing#download_massive_assign_definers_excel_format', via: :get, as: 'brc_managing_download_massive_assign_definers_excel_format'

  match 'brc/download_bonus_defined_excel_format/:brc_process_id', to: 'brc_managing#download_bonus_defined_excel_format', via: :get, as: 'brc_managing_download_bonus_defined_excel_format'
  match 'brc/massive_charge_bonus_calculated/:brc_process_id', to: 'brc_managing#massive_charge_bonus_calculated', via: :get, as: 'brc_managing_massive_charge_bonus_calculated'
  match 'brc/massive_charge_bonus_calculated/:brc_process_id', to: 'brc_managing#massive_charge_bonus_calculated', via: :post, as: 'brc_managing_massive_charge_bonus_calculated'
  match 'brc/download_massive_charge_bonus_calculated_excel_format', to: 'brc_managing#download_massive_charge_bonus_calculated_excel_format', via: :get, as: 'brc_managing_download_massive_charge_bonus_calculated_excel_format'

  match 'brc/download_bonus_chosen_excel_format/:brc_process_id', to: 'brc_managing#download_bonus_chosen_excel_format', via: :get, as: 'brc_managing_download_bonus_chosen_excel_format'
  match 'brc/download_bonus_chosen_excel_format_2/:brc_process_id', to: 'brc_managing#download_bonus_chosen_excel_format_2', via: :get, as: 'brc_managing_download_bonus_chosen_excel_format_2'

  match 'brc/massive_choose_list/:brc_process_id', to: 'brc_managing#massive_choose_list', via: :get, as: 'brc_managing_massive_choose_list'
  match 'brc/massive_choose/:brc_process_id', to: 'brc_managing#massive_choose', via: :post, as: 'brc_managing_massive_choose'

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :integer          not null, primary key
#  orden      :integer
#  asunto     :string(255)
#  texto      :text
#  fecha      :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Notification < ActiveRecord::Base

  attr_accessible :asunto, :fecha, :orden, :texto

  validates :asunto, presence: true
  validates :orden, presence: true, numericality: { only_integer: true, greater_than: 0 }

  default_scope order('orden ASC, updated_at DESC')


  def self.actives_for_user(user_id)

    actives_notifications_no_filter = Notification.all

    filter_by_characteristics(actives_notifications_no_filter, user_id)

  end

  private

  def self.filter_by_characteristics(actives_notifications_no_filter, user_id)
    notifications_to_show = []

    user_characteristics = UserCharacteristic.find_all_by_user_id(user_id)

    actives_notifications_no_filter.each do |notification|
      notification_characteristics = NotificationCharacteristic.find_all_by_notification_id(notification.id)
      #solo se filtra si la notification  tiene alguna caracteristica asociada
      if notification_characteristics.count > 0
        notification_characteristics.each do |notification_characteristic|
          user_characteristics.each do |user_characteristic|
            if notification_characteristic.match_value.to_s == user_characteristic.valor.to_s
              notifications_to_show.push(notification) unless notifications_to_show.include?(notification)
              break
            end
          end
        end
      else
        #si no hay caracteristicas asociadas la notification, se muestra nomas
        notifications_to_show.push(notification) unless notifications_to_show.include?(notification)
      end
    end


    return notifications_to_show

  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_filter :authenticate_user
  before_filter :authenticate_user_admin

  def index
    @notifications = Notification.all
  end

  def show
    @notification = Notification.find(params[:id])
  end

  def new
    @notification = Notification.new
    @characteristics = Characteristic.all
    @characteristics_prev = {}
    @mostrar_todos = true
  end

  def edit
    @notification = Notification.find(params[:id])

    @characteristics = Characteristic.all

    @characteristics_prev = {}

    if NotificationCharacteristic.find_all_by_notification_id(params[:id]).count > 0

      @characteristics.each do |characteristic|
        @characteristics_buffer = []
        NotificationCharacteristic.where(:notification_id => params[:id], :characteristic_id => characteristic.id).each do |notification_characteristic|
          @characteristics_buffer.push(notification_characteristic.match_value)
        end
        if @characteristics_buffer.length > 0
          @characteristics_prev[characteristic.id] = @characteristics_buffer
        end
      end
      @mostrar_todos = false
    else
      @mostrar_todos = true
    end

  end

  def create

    @notification = Notification.new(params[:notification])
    @notification.fecha = lms_time

    if @notification.save
      save_characteristics @notification.id
      reorder_notifications
      flash[:success] = t('activerecord.success.model.notification.create_ok')
      redirect_to notifications_url
    else
      render action: 'new'
    end


  end

  def update

    @notification = Notification.find(params[:id])

    prev_orden = @notification.orden

    if @notification.update_attributes(params[:notification])

      save_characteristics @notification.id

      reorder_notifications if prev_orden != @notification.orden

      flash[:success] = t('activerecord.success.model.notification.update_ok')
      redirect_to notifications_url
    else
      render action: 'edit'
    end

  end

  def destroy

    @notification = Notification.find(params[:id])
    @notification.destroy
    reorder_notifications

    flash[:success] = t('activerecord.success.model.notification.delete_ok')
    redirect_to notifications_url

  end

  private

    def reorder_notifications

      Notification.all.each_with_index do |notification, index|

        notification.orden = index + 1
        notification.save

      end

    end

    def reorder_notifications_(notification, prev_orden)

      Notification.all.each do |n|

        if n.id != notification.id

          if prev_orden < notification.orden

            if n.orden > prev_orden && n.orden <= notification.orden

              n.orden = n.orden - 1
              n.orden.save

            end

          elsif prev_orden > notification.orden

            if n.orden >= notification.orden && n.orden < prev_orden

              n.orden = n.orden + 1
              n.orden.save

            end

          end

        end

      end

    end

  def save_characteristics(notification_id)

    # se actualizan las characteristics asociadas para filtrar
    @characteristics = Characteristic.all
    NotificationCharacteristic.delete_all(:notification_id => notification_id)

    if !params[:notification_todos]
      if params[:characteristic]
        @characteristics.each do |characteristic|
          params[:characteristic][characteristic.id.to_s.to_sym].slice! 0
          params[:characteristic][characteristic.id.to_s.to_sym].each do |match_value|
            NotificationCharacteristic.new(:notification_id => notification_id, :characteristic_id => characteristic.id, :match_value => match_value).save!
          end
        end
      end
    end

  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for @notification, html: {class: 'form-horizontal'} do |f| %>

  <div class="panel panel-default">
    <div class="panel-body">

      <legend>Datos del aviso</legend>

      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group <%= field_with_errors f, :nombre %>">

        <%= f.label :orden, 'Orden', class: 'col-md-3 control-label' %>

        <div class="col-md-9">

          <%= f.number_field :orden, class: 'form-control' %>

        </div>

      </div>

      <div class="form-group <%= field_with_errors f, :nombre %>">

        <%= f.label :asunto, 'Asunto', class: 'col-md-3 control-label' %>

        <div class="col-md-9">

          <%= f.text_field :asunto, class: 'form-control' %>

        </div>

      </div>





      <div class="form-group">

        <div class="col-md-3 control-label">Mostrar a todos</div>
        <div class="col-md-9">

          <input type="checkbox" id="notification_todos" name="notification_todos" <%= 'checked=checked' if @mostrar_todos %> value="1" onchange="toggle_chars_filters();">
          <script>
            $('#notification_todos').bootstrapSwitch({
              onColor: 'success',
              onText: "Sí",
              offColor: 'danger',
              offText: "No"
            });

            function toggle_chars_filters() {

              if ($('#notification_todos').is(':checked')) {
                $('#chars_filters_container').hide();
              } else {
                $('#chars_filters_container').show();
              }
            }

            $(document).ready(function () {
              toggle_chars_filters();
            });

          </script>
          <%= render partial: 'characteristics/external_form_filter' %>
        </div>
      </div>



      <div class="form-group">

        <%= f.label :texto, 'Texto', class: 'col-md-3 control-label'%>

        <div class="col-md-9">

          <%= f.text_area :texto, rows: '5', class: 'form-control' %>



          <br>
          <br>
          <div class="row">
            <div class="col-md-3">
              <a><i class="fa fa-desktop"></i> Inicio</a>
            </div>
            <div class="col-md-9">
              <%= '<a><i class="fa fa-desktop"></i> Inicio</a>' %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-3">
              <a><i class="fa fa-book"></i> Cursos</a>
            </div>
            <div class="col-md-9">
              <%= '<a><i class="fa fa-book"></i> Cursos</a>' %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-3">
              <a><i class="fa fa-folder-o"></i> Biblioteca</a>
            </div>
            <div class="col-md-9">
              <%= '<a><i class="fa fa-folder-o"></i> Biblioteca</a>' %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-3">
              <a><i class="fa fa-comment-o"></i> Mesa de ayuda</a>
            </div>
            <div class="col-md-9">
              <%= '<a><i class="fa fa-comment-o"></i> Mesa de ayuda</a>' %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-3">
              <a><i class="fa fa-stack-overflow"></i> Gestión de la capacitación</a>
            </div>
            <div class="col-md-9">
              <%= '<a><i class="fa fa-stack-overflow"></i> Gestión de la capacitación</a>' %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-3">
              <a><i class="fa fa-pencil"></i> Gestión del desempeño</a>
            </div>
            <div class="col-md-9">
              <%= '<a><i class="fa fa-pencil"></i> Gestión del desempeño</a>' %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-3">
              <a><i class="fa fa-file-text-o"></i> Ficha de usuario</a>
            </div>
            <div class="col-md-9">
              <%= '<a><i class="fa fa-file-text-o"></i> Ficha de usuario</a>' %>
            </div>
          </div>

        </div>

      </div>
    </div>
    <div class="panel-footer clearfix">

      <div class="pull-right">

        <%= f.submit 'Guardar', class: 'btn btn-primary' %>

      </div>

    </div>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <%= link_to '<i class="fa fa-arrow-left"></i> Volver a la lista de avisos'.html_safe, notifications_path, class: 'btn btn-default', tabindex: '-1' %>
  </div>
  <div class="col-md-6">
    <h1 class="page-title txt-color-blueDark">
      <i class="fa fa-comment-o"></i>
      Avisos
      <span>> Editar aviso </span>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form' %>

  </div>
</div>

app/views/notifications/index.html.erb
<h1 class="page-title txt-color-blueDark">
  <i class="fa fa-comment-o"></i>
  Avisos
  <span>> Lista de avisos </span>
</h1>

<div class="panel panel-default">
  <div class="panel-body">


    <legend>Lista de avisos</legend>

    <table class="table table-striped table-hover table-bordered">

      <thead>

        <tr>
          <th>Orden</th>
          <th>Asunto</th>
          <th>Texto</th>
          <th>Fecha</th>
          <th colspan="2">
            <%= link_to 'Publicar un nuevo aviso', new_notification_path %>
          </th>
        </tr>

      </thead>

      <tbody>

      <% @notifications.each do |notification| %>
        <tr>
          <td><%= notification.orden %></td>
          <td><%= notification.asunto %></td>
          <td><%= notification.texto.html_safe %></td>
          <td>

            <%= (localize notification.fecha, format: :day_snmonth_year) if notification.fecha %>
          </td>

          <td><%= link_to 'Editar', edit_notification_path(notification) %></td>
          <td><%= link_to 'Eliminar', notification, method: :delete, data: { confirm: '¿Está seguro de eliminar el aviso?' } %></td>
        </tr>
      <% end %>

      </tbody>

    </table>
  </div>
</div>

app/views/notifications/new.html.erb
<div class="row">
  <div class="col-md-3">
    <%= link_to '<i class="fa fa-arrow-left"></i> Volver a la lista de avisos'.html_safe, notifications_path, class: 'btn btn-default', tabindex: '-1' %>
  </div>
  <div class="col-md-6">
    <h1 class="page-title txt-color-blueDark">
      <i class="fa fa-comment-o"></i>
      Avisos
      <span>> Crear un nuevo aviso </span>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form' %>

  </div>
</div>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Orden:</b>
  <%= @notification.orden %>
</p>

<p>
  <b>Asunto:</b>
  <%= @notification.asunto %>
</p>

<p>
  <b>Texto:</b>
  <%= @notification.texto %>
</p>

<p>
  <b>Fecha:</b>
  <%= @notification.fecha %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>