config/routes.rb
  match 'lms_managing_define/show_program/:program_id', to: 'lms_managing_define#show_program', via: :get, as: 'lms_managing_define_show_program'

  match 'lms_managing_define/new_course', to: 'lms_managing_define#new_course', via: :get, as: 'lms_managing_define_new_course'
  match 'lms_managing_define/create_course', to: 'lms_managing_define#create_course', via: :post, as: 'lms_managing_define_create_course'
  match 'lms_managing_define/edit_course/:course_id', to: 'lms_managing_define#edit_course', via: :get, as: 'lms_managing_define_edit_course'
  match 'lms_managing_define/update_course/:course_id', to: 'lms_managing_define#update_course', via: :post, as: 'lms_managing_define_update_course'
  match 'lms_managing_define/show_course/:course_id', to: 'lms_managing_define#show_course', via: :get, as: 'lms_managing_define_show_course'
  match 'lms_managing_define/edit_course_image/:course_id', to: 'lms_managing_define#edit_course_image', via: :get, as: 'lms_managing_define_edit_course_image'
  match 'lms_managing_define/update_course_image/:course_id', to: 'lms_managing_define#update_course_image', via: :post, as: 'lms_managing_define_update_course_image'

  match 'lms_managing_define/new_unit/:course_id', to: 'lms_managing_define#new_unit', via: :get, as: 'lms_managing_define_new_unit'
  match 'lms_managing_define/create_unit/:course_id', to: 'lms_managing_define#create_unit', via: :post, as: 'lms_managing_define_create_unit'
  match 'lms_managing_define/edit_unit/:unit_id', to: 'lms_managing_define#edit_unit', via: :get, as: 'lms_managing_define_edit_unit'
  match 'lms_managing_define/update_unit/:unit_id', to: 'lms_managing_define#update_unit', via: :post, as: 'lms_managing_define_update_unit'

  match 'lms_managing_define/new_evaluation/:course_id', to: 'lms_managing_define#new_evaluation', via: :get, as: 'lms_managing_define_new_evaluation'
  match 'lms_managing_define/create_evaluation/:course_id', to: 'lms_managing_define#create_evaluation', via: :post, as: 'lms_managing_define_create_evaluation'
  match 'lms_managing_define/edit_evaluation/:evaluation_id', to: 'lms_managing_define#edit_evaluation', via: :get, as: 'lms_managing_define_edit_evaluation'
  match 'lms_managing_define/update_evaluation/:evaluation_id', to: 'lms_managing_define#update_evaluation', via: :post, as: 'lms_managing_define_update_evaluation'

  match 'lms_managing_define/new_poll/:course_id', to: 'lms_managing_define#new_poll', via: :get, as: 'lms_managing_define_new_poll'
  match 'lms_managing_define/create_poll/:course_id', to: 'lms_managing_define#create_poll', via: :post, as: 'lms_managing_define_create_poll'
  match 'lms_managing_define/edit_poll/:poll_id', to: 'lms_managing_define#edit_poll', via: :get, as: 'lms_managing_define_edit_poll'
  match 'lms_managing_define/update_poll/:poll_id', to: 'lms_managing_define#update_poll', via: :post, as: 'lms_managing_define_update_poll'

  match 'lms_managing_define/show_study_plan/:program_id', to: 'lms_managing_define#show_study_plan', via: :get, as: 'lms_managing_define_show_study_plan'
  match 'lms_managing_define/add_study_plan/:program_id', to: 'lms_managing_define#add_study_plan', via: :get, as: 'lms_managing_define_add_study_plan'
  match 'lms_managing_define/create_study_plan/:program_id', to: 'lms_managing_define#create_study_plan', via: :post, as: 'lms_managing_define_create_study_plan'

  match 'lms_managing_execute/massive_charge_enrollments', to: 'lms_managing_execute#massive_charge_enrollments', via: :get, as: 'lms_managing_execute_massive_charge_enrollments'
  match 'lms_managing_execute/massive_charge_enrollments', to: 'lms_managing_execute#massive_charge_enrollments', via: :post, as: 'lms_managing_execute_massive_charge_enrollments'
  match 'lms_managing_execute/massive_charge_enrollments_download_format', to: 'lms_managing_execute#massive_charge_enrollments_download_format', via: :get, as: 'lms_managing_execute_massive_charge_enrollments_download_format'

  match 'lms_managing_execute/enroll', to: 'lms_managing_execute#enroll', via: :get, as: 'lms_managing_show_enroll'
  match 'lms_managing_execute/enroll/:pill_open', to: 'lms_managing_execute#enroll', via: :get, as: 'lms_managing_show_enroll_pill_open'
  match 'lms_managing_execute/enroll_people', to: 'lms_managing_execute#enroll_1_people', via: :post, as: 'lms_managing_show_list_to_enroll_users'
  match 'lms_managing_execute/remove_user/:user_id', to: 'lms_managing_execute#remove_user_from_list', via: :post, as: 'lms_managing_remove_user_from_list'
  match 'lms_managing_execute/enroll_found_people', to: 'lms_managing_execute#enroll_1_people', via: :post, as: 'lms_managing_show_list_found_users'
  match 'lms_managing_execute/enroll_courses', to: 'lms_managing_execute#enroll_2_courses', via: :post, as: 'lms_managing_show_list_to_enroll_courses'
  match 'lms_managing_execute/remove_course/:program_course_id', to: 'lms_managing_execute#remove_course_from_list', via: :post, as: 'lms_managing_remove_course_from_list'
  match 'lms_managing_execute/enroll_dates', to: 'lms_managing_execute#enroll_3_dates', via: :post, as: 'lms_managing_show_enroll_dates'
  match 'lms_managing_execute/save_dates', to: 'lms_managing_execute#save_dates_to_course', via: :post, as:'lms_managing_save_dates_to_course'
  match 'lms_managing_execute/enroll_confirm', to: 'lms_managing_execute#enroll_4_confirm', via: :post, as: 'lms_managing_show_enroll_confirmation'
  match 'lms_managing_execute/save_enroll', to: 'lms_managing_execute#enroll_5_enroll', via: :post, as: 'lms_managing_execute_save_enroll'

  match 'lms_managing_execute/pci/list_courses', to: 'lms_managing_execute#pci_list_courses', via: :get, as: 'lms_managing_execute_pci_list_courses'
  match 'lms_managing_execute/pci/:program_course_id', to: 'lms_managing_execute#pci_program_course', via: :get, as: 'lms_managing_execute_pci_program_course'
  match 'lms_managing_execute/pci/:program_course_id/new', to: 'lms_managing_execute#program_course_instance_new', via: :get, as: 'lms_managing_execute_pci_new'
  match 'lms_managing_execute/pci/:program_course_id/create', to: 'lms_managing_execute#program_course_instance_create', via: :post, as: 'lms_managing_execute_pci_create'
  match 'lms_managing_execute/pci/:program_course_instance_id/destroy', to: 'lms_managing_execute#program_course_instance_destroy', via: :delete, as: 'lms_managing_execute_pci_destroy'
  match 'lms_managing_execute/pci/:program_course_instance_id/edit_dates', to: 'lms_managing_execute#program_course_instance_edit_dates', via: :get, as: 'lms_managing_execute_pci_edit_dates'
  match 'lms_managing_execute/pci/:program_course_instance_id/update_dates', to: 'lms_managing_execute#program_course_instance_update_dates', via: :post, as: 'lms_managing_execute_pci_update_dates'

  match 'lms_managing_execute/pci/:program_course_instance_id/search_add_manager', to: 'lms_managing_execute#program_course_instance_search_add_manager', via: :get, as: 'lms_managing_execute_pci_search_add_manager'
  match 'lms_managing_execute/pci/:program_course_instance_id/search_add_manager', to: 'lms_managing_execute#program_course_instance_search_add_manager', via: :post, as: 'lms_managing_execute_pci_search_add_manager'
  match 'lms_managing_execute/pci/:program_course_instance_id/add_manager/:user_id', to: 'lms_managing_execute#program_course_instance_add_manager', via: :get, as: 'lms_managing_execute_pci_add_manager'
  match 'lms_managing_execute/pci/:program_course_instance_id/remove_manager/:user_id', to: 'lms_managing_execute#program_course_instance_remove_manager', via: :get, as: 'lms_managing_execute_pci_remove_manager'

  match 'lms_managing_execute/enrollment/list_courses', to: 'lms_managing_execute#enrollment_list_courses', via: :get, as: 'lms_managing_execute_enrollment_list_courses'
  match 'lms_managing_execute/enrollment/:program_course_id', to: 'lms_managing_execute#enrollment_program_course', via: :get, as: 'lms_managing_execute_enrollment_program_course'

  match 'lms_managing_execute/enrollment/:program_course_instance_id/enroll', to: 'lms_managing_execute#enrollment_enroll', via: :get, as: 'lms_managing_execute_enrollment_enroll'

  match 'lms_managing_execute/enrollment/:program_course_instance_id/delete_enrollments', to: 'lms_managing_execute#enrollment_delete_enrollments', via: :get, as: 'lms_managing_execute_enrollment_delete_enrollments'
  match 'lms_managing_execute/enrollment/:program_course_instance_id/destroy_enrollments', to: 'lms_managing_execute#enrollment_destroy_enrollments', via: :post, as: 'lms_managing_execute_enrollment_destroy_enrollments'
  match 'lms_managing_execute/enrollment/:program_course_instance_id/list', to: 'lms_managing_execute#enrollment_list', via: :get, as: 'lms_managing_execute_enrollment_list'

  match 'lms_managing_execute/enrollment/:program_course_instance_id/enroll/:pill_open', to: 'lms_managing_execute#enrollment_enroll', via: :get, as: 'lms_managing_execute_enrollment_enroll_pill_open'
  match 'lms_managing_execute/pci/:program_course_instance_id/enroll_people', to: 'lms_managing_execute#enroll_from_instances_1_people', via: :post, as: 'lms_managing_show_list_to_enroll_from_instances_users'
  match 'lms_managing_execute/pci/:program_course_instance_id/enroll_confirm', to: 'lms_managing_execute#enroll_from_instances_2_confirm', via: :post, as: 'lms_managing_show_enroll_from_instances_confirmation'
  match 'lms_managing_execute/pci/:program_course_instance_id/save_enroll', to: 'lms_managing_execute#enroll_from_instances_3_enroll', via: :post, as: 'lms_managing_execute_save_enroll_from_instances'
  match 'lms_managing_execute/pci/:program_course_instance_id/delete_people/:user_id', to: 'lms_managing_execute#remove_user_from_instance_list', via: :post, as: 'lms_managing_remove_user_from_instance_list'

app/models/enrollment.rb
# == Schema Information
#
# Table name: enrollments
#
#  id                  :integer          not null, primary key
#  user_id             :integer
#  program_id          :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  level_id            :integer
#  program_instance_id :integer
#  aprobado            :boolean
#  active              :boolean          default(TRUE)
#

class Enrollment < ActiveRecord::Base
  
  belongs_to :program
  belongs_to :program_instance
  belongs_to :user
  belongs_to :level

  has_many :user_courses
  has_many :program_courses, through: :user_courses
  
  attr_accessible :program, :user, :level, :program_instance, :aprobado, :active

  validates :program, presence: true
  validates :user, presence: true
  validates :user_id, uniqueness: { scope: [:program_id, :program_instance_id] }
  validates :level, presence: true


  validate :program_level
 
  def program_level
  	
  	unless level_id.nil?

  		if Level.find(level_id).program.id != program_id
	      errors.add(:mismatch_program_level, 'El nivel debe pertenecer al mismo programa')
	    end	

  	end
    
  end

  def user_courses_order_by_nombre_secuencia
    self.user_courses.joins(:course).where('anulado = ?', 0).order('nombre, id')
  end

  def user_courses_order_by_nombre_asc_secuencia_desc
    self.user_courses.joins(:course).where('anulado = ?', 0).order('nombre, id DESC')
  end

  def user_courses_by_program_course_secuencia_desc(program_course)
    self.user_courses.where('program_course_id = ? AND anulado = ?', program_course.id, 0).reorder('id DESC')
  end

  def years
    f = self.user_courses.where('desde IS NOT NULL').reorder('desde DESC').pluck(:desde).map { |fecha| fecha.year }
    f.uniq
  end

  def visible_program_courses_by_year_ordered(year)
    self.program_courses.joins(:course).where('hidden_in_user_courses_list = ? AND year(user_courses.desde) = ?', false, year).uniq.order('courses.nombre')
  end

end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/consultar_resultados_grupo_f.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 panel_content_info-<%= $current_domain %>">

    <legend class="text-center">Gestionar <%= @program_course.program.nombre %></legend>

    <div class="row">
      <div class="col-md-3 text-right">
        <strong>Curso</strong>
      </div>
      <div class="col-md-8">
        <%= @program_course.course.nombre %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 text-right">
        <strong>Nota mínima</strong>
      </div>
      <div class="col-md-8">
        <%= @program_course.course.nota_minima %>
      </div>
    </div>

    <div class="form-actions">
      <%= link_to 'Volver', enrollments_ver_programa_path(@program_course.program), tabindex: '-1' %>
    </div>

  </div>
</div>

  <br>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <div class="panel">
        <div class="panel-body">

          <table class="table table-striped table-hover table-bordered">

            <thead>

            <tr>
              <th width="1%">#</th>
              <th>Código</th>
              <th>Apellidos</th>
              <th>Nombre</th>
              <th>Desde</th>
              <th>Hasta</th>
              <th>Oportunidad</th>
              <th>Estado</th>
              <th>Nota</th>
              <th>Inicio Real</th>
              <th>Fin Real</th>


            </tr>

            </thead>

            <tbody>

            <% @user_courses.each_with_index do |uc, index| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= uc.enrollment.user.codigo %></td>
                <td><%= uc.enrollment.user.apellidos %></td>
                <td><%= uc.enrollment.user.nombre %></td>
                <td><%= (localize  uc.desde, format: :day_snmonth_year) %></td>
                <td><%= (localize  uc.hasta, format: :day_snmonth_year) %></td>
                <td><%= uc.numero_oportunidad %></td>
                <td>

                  <% estado = uc.estado lms_time %>

                  <% if estado == :anulado %>
                    <span class="label label-default">Anulado</span>
                  <% elsif estado == :no_iniciado %>
                    <span class="label label-default">No iniciado</span>
                  <% elsif estado == :en_progreso %>
                    <span class="label label-primary">En progreso</span>
                  <% elsif estado == :plazo_vencido %>
                    <span class="label label-danger">Plazo Vencido</span>
                  <% elsif estado == :aprobado %>
                    <% if uc.nota %>
                      <span class="label label-success">Aprobado</span>
                    <% else %>
                      <span class="label label-success">Cursado</span>
                    <% end %>
                  <% elsif estado == :reprobado %>
                    <span class="label label-danger">Reprobado</span>
                  <% end %>

                </td>

                <td>

                  <% if estado == :aprobado && uc.nota %>
                <span class="label label-success">

                  <%= format_nota(uc.nota) %> <%= tipo_nota(uc.course) %>

                </span>
                  <% elsif estado == :reprobado && uc.nota  %>
                <span class="label label-danger">
                  <%= format_nota(uc.nota) %> <%= tipo_nota(uc.course) %>
                </span>
                  <% end %>

                </td>
                <td><%= localize uc.inicio, format: :day_snmonth_year if uc.inicio %></td>
                <td><%= localize uc.fin, format: :day_snmonth_year if uc.iniciado && uc.finalizado %></td>

              </tr>

            <% end %>

            </tbody>
          </table>

        </div>
      </div>


    </div>
  </div>

app/views/enrollments/define_anula_matricula.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 panel_content_info-<%= $current_domain %>">

    <legend class="text-center">Gestionar <%= @program_course.program.nombre %></legend>

    <div class="row">
      <div class="col-md-3 text-right">
        <strong>Curso</strong>
      </div>
      <div class="col-md-8">
        <%= @program_course.course.nombre %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 text-right">
        <strong>Nota mínima</strong>
      </div>
      <div class="col-md-8">
        <%= @program_course.course.nota_minima %>
      </div>
    </div>

    <div class="form-actions">
      <%= link_to 'Volver', enrollments_ver_programa_path(@program_course.program), tabindex: '-1' %>
    </div>

  </div>
</div>



<br>

<% user_course = UserCourse.new %>

<%= form_for user_course, url: enrollments_update_anula_matricula_path(@program_course, @grupo), html: {class: 'form-horizontal'} do |f| %>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <legend class="text-center">Anular matrícula de alumnos</legend>

      <label><strong>Fechas en las que se dictó el curso</strong></label>

      <span class="label label-primary">
        <%= (localize  @user_courses.first.desde, format: :day_snmonth) %>
      </span>

      <span class="label label-primary">
        <%= (localize  @user_courses.first.hasta, format: :day_snmonth) %>
      </span>

    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <table class="table table-striped table-hover table-bordered">

        <thead>

        <tr>

          <th width="1%">#</th>
          <th>Apellidos</th>
          <th>Nombre</th>
          <th>Matrícula</th>

        </tr>

        </thead>

        <tbody>

        <% @user_courses.each_with_index do |uc, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= uc.enrollment.user.apellidos %></td>
            <td><%= uc.enrollment.user.nombre %></td>
            <td>

              <div>

                <% if uc.anulado %>

                  <%= check_box('user_id', uc.id, {class: 'check_user', checked: 'checked'}, uc.id.to_s, '0')%>

                <% else %>

                  <%= check_box('user_id', uc.id, {class: 'check_user'}, uc.id.to_s, '0')%>

                <% end %>

                <script>
                    $('#user_id_<%= uc.id %>').bootstrapSwitch({
                        onColor: 'danger',
                        onText: "<nobr>&nbsp;&nbsp; <i class='fa fa-times'></i> Anulado &nbsp;&nbsp;</nobr>",
                        offColor: 'success',
                        offText: "<nobr>&nbsp;&nbsp; <i class='fa fa-check'></i> Vigente &nbsp;&nbsp;</nobr>"
                    });
                </script>

              </div>

            </td>


          </tr>

        <% end %>


        </tbody>

      </table>




    </div>
  </div>

    <div class="row">

      <div class="col-md-8 col-md-offset-2 text-center">
        <hr>
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>

      </div>
    </div>

<% end %>

app/views/enrollments/define_aplica_sence.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 panel_content_info-<%= $current_domain %>">

    <legend class="text-center">Gestionar <%= @program_course.program.nombre %></legend>

    <div class="row">
      <div class="col-md-3 text-right">
        <strong>Curso</strong>
      </div>
      <div class="col-md-8">
        <%= @program_course.course.nombre %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 text-right">
        <strong>Nota mínima</strong>
      </div>
      <div class="col-md-8">
        <%= @program_course.course.nota_minima %>
      </div>
    </div>

    <div class="form-actions">
      <%= link_to 'Volver', enrollments_ver_programa_path(@program_course.program), tabindex: '-1' %>
    </div>

  </div>
</div>



<br>

<% user_course = UserCourse.new %>

<%= form_for user_course, url: enrollments_update_aplica_sence_path(@program_course, @grupo), html: {class: 'form-horizontal'} do |f| %>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <legend class="text-center">Definir la aplicación de Sence</legend>

      <label><strong>Fechas en las que se dictó el curso</strong></label>

      <span class="label label-primary">
        <%= (localize  @user_courses.first.desde, format: :day_snmonth) %>
      </span>

      <span class="label label-primary">
        <%= (localize  @user_courses.first.hasta, format: :day_snmonth) %>
      </span>

    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <table class="table table-striped table-hover table-bordered">

        <thead>

        <tr>

          <th width="1%">#</th>
          <th>Apellidos</th>
          <th>Nombre</th>
          <th>Sence</th>

        </tr>

        </thead>

        <tbody>

        <% @user_courses.each_with_index do |uc, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= uc.enrollment.user.apellidos %></td>
            <td><%= uc.enrollment.user.nombre %></td>
            <td>

              <div class="make-switch switch-small" data-on="success" data-off="danger" data-on-label="<nobr>&nbsp;&nbsp;<i class='fa fa-check'></i> Sí &nbsp;&nbsp;</nobr>" data-off-label="<nobr>&nbsp;&nbsp;<i class='fa fa-times'></i> No &nbsp;&nbsp;</nobr>">

                <% if uc.aplica_sence %>

                  <%= check_box('user_id', uc.id, {class: 'check_user', checked: 'checked'}, uc.id.to_s, '0')%>

                <% else %>

                  <%= check_box('user_id', uc.id, {class: 'check_user'}, uc.id.to_s, '0')%>

                <% end %>

              </div>

            </td>


          </tr>

        <% end %>


        </tbody>

      </table>




    </div>
  </div>

    <div class="row">

      <div class="col-md-8 col-md-offset-2 text-center">
        <hr>
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>

      </div>
    </div>

<% end %>

app/views/enrollments/register_poll.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 panel_content_info-<%= $current_domain %>">

    <legend class="text-center">Gestionar <%= @program_course.program.nombre %></legend>

    <div class="row">
      <div class="col-md-3 text-right">
        <strong>Curso</strong>
      </div>
      <div class="col-md-8">
        <%= @program_course.course.nombre %>
      </div>
    </div>


    <div class="form-actions">
      <%= link_to 'Volver', enrollments_ver_programa_path(@program_course.program), tabindex: '-1' %>
    </div>

  </div>
</div>


<% summary = ProgramCoursePollSummary.new %>

<%= form_for summary, url: enrollments_update_poll_path(@program_course, @grupo), html: {class: 'form-horizontal'} do |f| %>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <legend class="text-center">Encuesta</legend>

      <label><strong>Fechas en las que se dictó el curso</strong></label>

      <span class="label label-primary">
        <%= (localize  @user_course.desde, format: :day_snmonth_year) %>
      </span>

      <span class="label label-primary">
        <%= (localize  @user_course.hasta, format: :day_snmonth_year) %>
      </span>

    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <% poll = @course.polls.where('tipo_satisfaccion = ?', true).first %>

      <% master_questions = poll.master_poll.master_poll_questions %>

      <% if poll.master_poll.modo_grid %>

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>

              </th>

              <% lista_alternativas = nil %>
              <% max = 0 %>

              <% master_questions.each do |master_question| %>

                <% if master_question.master_poll_alternatives.length > max %>

                  <% lista_alternativas = master_question.master_poll_alternatives %>

                  <% max = master_question.master_poll_alternatives.length %>

                <% end %>

              <% end %>

              <% lista_alternativas.each_with_index do |alt| %>

                <th>
                  <%= alt.letra %>. <%= alt.texto.html_safe %>
                </th>

              <% end %>

            </tr>
          </thead>

          <tbody>

            <% master_questions.each_with_index do |master_question, index| %>
              <tr>
                <td>
                  <strong><%= index+1 %>. </strong>
                  <%= master_question.texto.html_safe %>
                </td>

                <% index_a = 0 %>

                <% master_question.master_poll_alternatives.each do |alt| %>

                  <% poll_summary = ProgramCoursePollSummary.where('program_course_id = ? AND poll_id = ? AND master_poll_question_id = ? AND master_poll_alternative_id = ? AND grupo = ? ',
                                                                   @program_course.id, poll.id, master_question.id, alt.id, @grupo).first  %>

                  <td style="vertical-align:bottom">
                      <% valor = 0 %>
                      <% valor = poll_summary.numero_respuestas if poll_summary %>

                      <% if @course.poll_presencial %>

                        <%= number_field('poll_summary', alt.id, min: 0, value: valor, class: 'span12' )%>

                      <% else %>

                        <%= number_field('poll_summary', alt.id, min: 0, value: valor, readonly: 'readonly', class: 'span12' )%>

                      <% end %>

                  </td>

                  <% index_a += 1 %>

                <% end %>
                <% if max > index_a %>
                  <% (index_a..max-1).each do |faltante| %>
                    <td></td>
                  <% end %>
                <% end %>
              </tr>

            <% end %>

          </tbody>

        </table>






      <% else %>

        <% master_questions.each_with_index do |master_question, index| %>

          <div class="row pregunta-evaluacion-<%= $current_domain %>">

            <div class="col-md-12">

              <div class="row">
                <div class="col-md-10">
                  <strong><%= index+1 %>. </strong>
                  <%= master_question.texto.html_safe %>
                </div>
                <div class="col-md-2">

                </div>
              </div>
              <br>

              <% master_question.master_poll_alternatives.each_with_index do |alt, index_a| %>

                <% poll_summary = ProgramCoursePollSummary.where('program_course_id = ? AND poll_id = ? AND master_poll_question_id = ? AND master_poll_alternative_id = ? AND grupo = ? ',
                                                                 @program_course.id, poll.id, master_question.id, alt.id, @grupo).first  %>

                <div class="row alternativa-pregunta-evaluacion">
                  <div class="col-md-1 text-right">
                    <strong><%= alt.letra %>. </strong>
                  </div>
                  <div class="col-md-2">
                    <% valor = 0 %>
                    <% valor = poll_summary.numero_respuestas if poll_summary %>

                    <% if @course.poll_presencial %>

                      <%= number_field('poll_summary', alt.id, min: 0, value: valor, class: 'span12' )%>

                    <% else %>

                      <%= number_field('poll_summary', alt.id, min: 0, value: valor, readonly: 'readonly', class: 'span12' )%>

                    <% end %>

                  </div>
                  <div class="col-md-9">
                    <%= alt.texto.html_safe %>
                  </div>

                </div>


              <% end %>

            </div>

          </div>

        <% end %>

      <% end %>

    </div>
  </div>

  <% if @course.poll_presencial %>
    <div class="row">

      <div class="col-md-8 col-md-offset-2 text-center">
        <hr>
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>

      </div>
    </div>
  <% end %>

<% end %>